# Running a powerflow given injection data

This notebook will outline how to run powerflow algorithms given a grid and injection snapshot. The example in this notebook includes an incomplete dataset, and some synthetic data and powerflow tuning are utilized to run a convergent powerflow. The specifics of the approach taken here are motivated, but leave much room for improvement!

In [1]:
import pypowsybl as pp
import pandas as pd
from pathlib import Path
import numpy as np

grid = pp.network.load(file='data/recollement-auto-20210101-0000-enrichi.xiidm.bz2')
print('Grid model loaded')

grid.get_generators()

Grid model loaded

,name,energy_source,target_p,min_p,max_p,min_q,max_q,rated_s,reactive_limits_kind,target_v,target_q,voltage_regulator_on,regulated_element_id,p,q,i,voltage_level_id,bus_id,connected
id,,,,,,,,,,,,,,,,,,,
.CTLO3GROUP.1,,HYDRO,NaN,0.0,15.0,NaN,NaN,NaN,CURVE,NaN,NaN,True,.CTLO3GROUP.1,NaN,NaN,NaN,.CTLHP3,.CTLHP3_0,True
.CTLO3GROUP.2,,HYDRO,NaN,0.0,15.0,NaN,NaN,NaN,CURVE,NaN,NaN,True,.CTLO3GROUP.2,NaN,NaN,NaN,.CTLHP3,.CTLHP3_1,True
ARGIAINF,,SOLAR,NaN,0.0,0.7,NaN,NaN,NaN,CURVE,NaN,NaN,False,ARGIAINF,NaN,NaN,NaN,ARGIAP3,,False
ARGOEIN2,,WIND,NaN,0.0,0.0,0.0,0.0,NaN,MIN_MAX,NaN,NaN,False,ARGOEIN2,NaN,NaN,NaN,ARGOEP4,ARGOEP4_0,True
ARGOEIN3,,WIND,NaN,0.0,14.4,NaN,NaN,NaN,CURVE,NaN,NaN,False,ARGOEIN3,NaN,NaN,NaN,ARGOEP4,ARGOEP4_0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YQUELING,,SOLAR,NaN,0.0,2.3,NaN,NaN,NaN,CURVE,NaN,NaN,False,YQUELING,NaN,NaN,NaN,YQUELP4,,False
YVETOINF,,SOLAR,NaN,0.0,0.4,NaN,NaN,NaN,CURVE,NaN,NaN,False,YVETOINF,NaN,NaN,NaN,YVETOP4,,False
YVETOING,,SOLAR,NaN,0.0,0.4,NaN,NaN,NaN,CURVE,NaN,NaN,False,YVETOING,NaN,NaN,NaN,YVETOP4,,False
YZEURIN2,,SOLAR,NaN,0.0,4.4,NaN,NaN,NaN,CURVE,NaN,NaN,False,YZEURIN2,NaN,NaN,NaN,YZEURP3,,False
YZEURIN1,,SOLAR,NaN,0.0,10.2,NaN,NaN,NaN,CURVE,NaN,NaN,False,YZEURIN1,NaN,NaN,NaN,YZEURP3,YZEURP3_0,True

This notebook uses injections that are in the .parquet format, for which we can use the pyarrow engine to read and convert them to a pandas dataframe. We can compare the below injected generator snapshot to the grid generator data above, noticing that much of the information is simply repeated, but that the critical values for `target_p` (the generator´s real power output) are included in the injection. These are necessary for us to be able to run a power flow.

In [2]:
#These snapshots are separated by element type, so we create a pandas dataframe for each of those we are interested in: the generators, loads and buses

df_inj_gen = pd.read_parquet("data/snapshot_gen_2021-01-01T00-00-00.parquet", engine="pyarrow")
df_inj_load = pd.read_parquet("data/snapshot_load_2021-01-01T00-00-00.parquet", engine="pyarrow")
df_inj_bus = pd.read_parquet("data/snapshot_bus_2021-01-01T00-00-00.parquet", engine="pyarrow")

#We can look into one of these snapshots to see what it contains
df_inj_gen

,datetime,id,name,energy_source,target_p,min_p,max_p,min_q,max_q,rated_s,...,i,voltage_level_id,bus_id,connected,substation_id,nominal_v,region_code,disaggregation_weight,online_capacity_total,actual_output_total
0,2021-01-01,.CTLO3GROUP.1,NaN,hydro,0.150,0.0,0.150,NaN,NaN,NaN,...,NaN,.CTLHP3,.CTLHP3_0,True,.CTLH,63.0,84,0.002712,55.315300,2667.0
1,2021-01-01,.CTLO3GROUP.2,NaN,hydro,0.150,0.0,0.150,NaN,NaN,NaN,...,NaN,.CTLHP3,.CTLHP3_1,True,.CTLH,63.0,84,0.002712,55.315300,2667.0
2,2021-01-01,ARGIAINF,NaN,solar,0.000,0.0,0.007,NaN,NaN,NaN,...,NaN,ARGIAP3,NaN,False,ARGIA,63.0,75,0.000000,18.229900,0.0
3,2021-01-01,ARGOEIN2,NaN,wind,0.000,0.0,0.000,0.0,0.0,NaN,...,NaN,ARGOEP4,ARGOEP4_0,True,ARGOE,90.0,32,0.000000,49.534698,372.0
4,2021-01-01,ARGOEIN3,NaN,wind,0.144,0.0,0.144,NaN,NaN,NaN,...,NaN,ARGOEP4,ARGOEP4_0,True,ARGOE,90.0,32,0.002907,49.534698,372.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5620,2021-01-01,YQUELING,NaN,solar,0.000,0.0,0.023,NaN,NaN,NaN,...,NaN,YQUELP4,NaN,False,YQUEL,90.0,28,0.000000,0.510000,0.0
5621,2021-01-01,YVETOINF,NaN,solar,0.000,0.0,0.004,NaN,NaN,NaN,...,NaN,YVETOP4,NaN,False,YVETO,90.0,28,0.000000,0.510000,0.0
5622,2021-01-01,YVETOING,NaN,solar,0.000,0.0,0.004,NaN,NaN,NaN,...,NaN,YVETOP4,NaN,False,YVETO,90.0,28,0.000000,0.510000,0.0
5623,2021-01-01,YZEURIN2,NaN,solar,0.000,0.0,0.044,NaN,NaN,NaN,...,NaN,YZEURP3,NaN,False,YZEUR,63.0,84,0.000000,5.722600,0.0
5624,2021-01-01,YZEURIN1,NaN,solar,0.000,0.0,0.102,NaN,NaN,NaN,...,NaN,YZEURP3,YZEURP3_0,True,YZEUR,63.0,84,0.017824,5.722600,0.0

## Injecting the data

To use this data in the powerflow, we will need to change the `target_p` column in the grid to match those in the injection data. Noting that the indexing on the injection (pandas) dataset is via the index number as default, and we must change it to the `id` in order to correctly match the generators to their injected power. You will notice that there is a multiplication factor of 100 present; this is due to the `target_p`s of this generator injection dataset being in per-units for a base power of 100MW. This is not the case for the `p0`s in the load injection dataset, which are given in MW.

In [3]:
df_inj_gen['target_p'] =  df_inj_gen['target_p'] *100

df_gens = grid.get_generators(attributes=['target_p']) 
df_gens.update(df_inj_gen.set_index('id'))
grid.update_generators(df=df_gens)

In much the same way, we can set the P values for our loads, and proceed with V and Q injection. In the case of this dataset, however, we do not have the V or Q data (you may check!). Nonetheless, we will be able to run a powerflow if we can come up with some feasible synthetic data. Below, we choose synthetic Q of zero, corresponding to a power factor of 1.0.

In [4]:
load_power_factor = 1.0 

df_loads = grid.get_loads(attributes=['p0'])
df_loads.update(df_inj_load.set_index('id'))
grid.update_loads(df=df_loads)

df_inj_load['q0'] = df_inj_load['p0'] * np.sqrt( (1-load_power_factor**2)/load_power_factor)
df_loads = grid.get_loads(attributes=['q0'])
df_loads.update(df_inj_load.set_index('id'))
grid.update_loads(df=df_loads)

We must also use synthetic data for the generators. Generators can either be PV with a voltage regulator (and `voltage_regulator_on = True`) or PQ (with `voltage_regulator_on = False`). For the PQ generators we can take the same approach as for the loads, and for the PV, the nominal voltage (`nominal_v`) of the connected voltage level is a sensible choice.

In [5]:
gen_power_factor = 1.0

# PQ generators
df_inj_pqgens = df_inj_gen.loc[df_inj_gen['voltage_regulator_on'] == False].copy()

df_inj_pqgens.loc[:, 'target_q'] = df_inj_pqgens['target_p'] * np.sqrt((1 - gen_power_factor**2) / gen_power_factor)

df_pqgens = grid.get_generators(attributes=['target_q'])
df_pqgens.update(df_inj_pqgens.set_index('id'))
grid.update_generators(df=df_pqgens)

# PV generators
df_inj_pvgens = df_inj_gen.loc[df_inj_gen['voltage_regulator_on'] == True].copy()

lookup_v = df_inj_bus.drop_duplicates(subset='voltage_level_id').set_index('voltage_level_id')['nominal_v']

df_inj_pvgens.loc[:, 'target_v'] = df_inj_pvgens['voltage_level_id'].map(lookup_v)

df_pvgens = grid.get_generators(attributes=['target_v'])
df_pvgens.update(df_inj_pvgens.set_index('id'))
grid.update_generators(df=df_pvgens)

We can use the `.validate()` function on our grid to check if it is set up correctly such that we can run a powerflow.

In [6]:
grid.validate()

PyPowsyblError: Dangling line '.SOTEL62SOTEL': p0 is invalid

This error is telling us there is an issue with (at least one of) our dangling lines. Dangling lines are the interconnections at the periphery of our grid, connecting to buses outside of the RTE dataset. These can export (or import) active and reactive power from/to our grid, and so we must also inject this data. Let's go with the simple  assumption that there is no power transfer.

In [7]:
df_dlines = grid.get_dangling_lines(attributes=['p0','q0']).copy()
df_dlines["p0"] = 0.0
df_dlines["q0"] = 0.0

grid.update_dangling_lines(df=df_dlines)

Now we can check again to see if we have all the required input data for the powerflow:

In [8]:
grid.validate()

This `STEADY_STATE_HYPOTHESIS` validation level is necessary for us to be able to run our powerflow. Now, we would expect that all of our generation, load, and dangling line powers will aggregate to give us something close to zero, with a tolarance for losses. Below we ensure this by scaling the generator power outputs to exactly match the load and dangling line demand total, with 3% allocated for losses.

In [9]:
mask_load = grid.get_loads()["connected"] == True
mask_gen = grid.get_generators()["connected"] == True
loss_margin_fraction = 0.03

total_load = grid.get_loads().loc[mask_load, "p0"].sum()
total_inter = grid.get_dangling_lines()["p0"].sum()
total_demand = total_load + total_inter
target_gen_value = total_demand * (1.0 + loss_margin_fraction)

gen_df = grid.get_generators().loc[mask_gen, ["target_p"]]
total_gen_available = gen_df["target_p"].sum()
scale_factor = target_gen_value / total_gen_available
gen_df["target_p"] *= scale_factor
grid.update_generators(df=gen_df)

final_gen_sum = grid.get_generators().loc[mask_gen, "target_p"].sum()
print(f"Generation scaled by {scale_factor:.4f} "
      f"({total_gen_available:.0f} MW -> {final_gen_sum:.0f} MW) "
      f"to match demand {total_demand:.0f} MW + {loss_margin_fraction*100:.0f}% losses")

Generation scaled by 0.7681 (86346 MW -> 66321 MW) to match demand 64389 MW + 3% losses

This is a significant rescaling! The previous generator power configuration was not realistic.

## Running the powerflow

We run the powerflow as below, and have a look at the results

In [10]:
results = pp.loadflow.run_ac(grid)
results

[ComponentResult(connected_component_num=0, synchronous_component_num=0, status=MAX_ITERATION_REACHED, status_text=Reached Newton-Raphson max iterations limit, iteration_count=22, reference_bus_id='CHAFFP7_0', slack_bus_results=[SlackBusResult(id='CHAFFP7_0', active_power_mismatch=-29.81158167067859)], distributed_active_power=336.2073763219124)]

The `status` component of our results is telling us that the powerflow algorithm failed to converge. This is okay, as we still haven´t looked into the various ways we can choose to run the powerflow. We have a good degree of flexibility when it comes to this, having access to two providers:

In [11]:
pp.loadflow.get_provider_names()
#pp.loadflow.get_default_provider() #Run to check which is in use

['DynaFlow', 'OpenLoadFlow']

We will use the default [OpenLoadFlow](https://powsybl.readthedocs.io/projects/powsybl-open-loadflow/en/latest/) provider, however [Dynawo](https://powsybl.readthedocs.io/projects/powsybl-dynawo/en/latest/) is another option. 

Now we can look at the parameters of our powerflow. The default ones are:

In [12]:
pp.loadflow.Parameters()

Parameters(voltage_init_mode=UNIFORM_VALUES, transformer_voltage_control_on=False, use_reactive_limits=True, phase_shifter_regulation_on=False, twt_split_shunt_admittance=False, shunt_compensator_voltage_control_on=False, read_slack_bus=True, write_slack_bus=True, distributed_slack=True, balance_type=PROPORTIONAL_TO_GENERATION_P_MAX, dc_use_transformer_ratio=True, countries_to_balance=[], component_mode=<ComponentMode.MAIN_CONNECTED: 0>, hvdc_ac_emulation=True, dc_power_factor=1.0, provider_parameters={})

We can leave these as is, but let´s change them in an effort to get convergence. In the script below you will see various changes to PowSyBl loadflow [parameters](https://powsybl.readthedocs.io/projects/powsybl-core/en/stable/simulation/loadflow/configuration.html) which should help our powerflow to converge.  There are long lists of 'provider parameters' which offer increased flexibility, and can be found on the corresponding provider´s documentation ( [Open Loadflow](https://powsybl.readthedocs.io/projects/powsybl-open-loadflow/en/latest/), [Dynawo](https://powsybl.readthedocs.io/projects/powsybl-dynawo/en/latest/)). It´s important to note that these provider parameters must be used as below, with all keys and values given as a string.

In [ ]:
ac_params = pp.loadflow.Parameters(
    voltage_init_mode=pp.loadflow.VoltageInitMode.DC_VALUES, # Initialize voltages as 1pu and voltage angles using a DC powerflow
    distributed_slack=False, # The active power mismatch won't be distributed over the network
    balance_type=pp.loadflow.BalanceType.PROPORTIONAL_TO_GENERATION_P, # The participation factors for slack distribution are calculated using 'target_p'
    transformer_voltage_control_on=False, # Transformer voltage regulating will not be allowed 
    shunt_compensator_voltage_control_on=False, # Shunt compensator voltage regulating will not be allowed 
    use_reactive_limits=False, # Since our dataset does not contain realistic q_max limits, we will ignore them

    provider_parameters={ 
        'maxNewtonRaphsonIterations': '20',
        'maxOuterLoopIterations': '20',
        'newtonRaphsonConvEpsPerEq': '1e-5', # Stopping criterion
        'slackBusPMaxMismatch': '1500.0', # Maximum active power mismatch considered acceptable

    }
)

Now we´ll try to run the powerflow again, also producing a report alongside it:

In [14]:
rep = pp.report.ReportNode()
results = pp.loadflow.run_ac(grid, parameters= ac_params, report_node= rep )
results
# rep # If we wish to read the report. It is very long, so only use if debugging!

[ComponentResult(connected_component_num=0, synchronous_component_num=0, status=CONVERGED, status_text=Converged, iteration_count=4, reference_bus_id='CHAFFP7_0', slack_bus_results=[SlackBusResult(id='CHAFFP7_0', active_power_mismatch=335.5056028433242)], distributed_active_power=0.0)]

The loadflow converged! We can look at a few key pieces of information from `results` if we choose (critically, `status=CONVERGED`!). The more interesting information, however, will come from inspecting our grid post-powerflow.

In [15]:
print(f"Status: {results[0].status_text}")
print(f"Iteration count: {results[0].iteration_count}")
print(f"Active power mismatch: {results[0].slack_bus_results[0].active_power_mismatch:.4f} MW")

df_buses = grid.get_buses()
df_vlevels = grid.get_voltage_levels()
df_buses = df_buses.merge(df_vlevels[['nominal_v']], left_on='voltage_level_id', right_index=True)
df_buses['v_pu'] = df_buses['v_mag'] / df_buses['nominal_v']

print(f"\n--- Bus Voltage Results ---")
print(f"Total buses: {len(df_buses)}")
print(f"\nVoltage magnitude (kV):")
print(df_buses['v_mag'].describe().to_string())
print(f"\nVoltage magnitude (pu):")
print(df_buses['v_pu'].describe().to_string())

out_of_range = df_buses[(df_buses['v_pu'] < 0.9) | (df_buses['v_pu'] > 1.1)]
print(f"\nBuses outside 0.9-1.1 pu: {len(out_of_range)} / {len(df_buses)}")

Status: Converged
Iteration count: 4
Active power mismatch: 335.5056 MW

--- Bus Voltage Results ---
Total buses: 6467

Voltage magnitude (kV):
count    6366.000000
mean      114.333159
std        91.875714
min        17.304170
25%        61.042707
50%        63.000000
75%       150.447843
max       410.441101

Voltage magnitude (pu):
count    6366.000000
mean        0.985774
std         0.031199
min         0.674515
25%         0.967579
50%         0.991107
75%         1.002392
max         1.182224

Buses outside 0.9-1.1 pu: 49 / 6467